name: Auto deploy

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: build
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }} #hostname of server
          username: ${{ secrets.USERNAME }} #username login to server
          password: ${{ secrets.PASSWORD }} #password login to server
          port: ${{ secrets.PORT }} #port of server - often port is 22
          script: | # run with multiple script
            cd work/auto-deploy-project-with-action/
            git pull origin master
      - name: build maven
        use: LucaFeger/action-maven-cli@1.1.0
        run: mvn clean install
