name: Auto deploy

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }} #hostname of server
          username: ${{ secrets.USERNAME }} #username login to server
          password: ${{ secrets.PASSWORD }} #password login to server
          port: ${{ secrets.PORT }} #port of server - often port is 22
          script: | # run with multiple script
            cd work/
            cd auto-deploy-project-with-action/
            docker build -t auto-deploy .
          run: docker run -p 443:8080 auto-deploy
